### ISSUE TITLE
Impersonate.do function order

### ISSUE THREAD

**Issue by Siyfion** [gwendall/meteor-impersonate#4]
@gwendall Alas, I thought we had it, but we don't (quite) yet...

``` javascript
Impersonate.do = function(userId, cb) {
  Meteor.call("impersonate", userId, function(err, _userId) {
    if (!!(cb && cb.constructor && cb.apply)) cb.apply(this, [err, _userId]);
    if (err) return;
    if (!Impersonate._user.get()) Impersonate._user.set(Meteor.userId()); // First impersonation
    Meteor.connection.setUserId(_userId);
  });
}

Impersonate.undo = function(cb) {
  Impersonate.do(Impersonate._user.get(), function(err, _userId) {
    if (!err) Impersonate._user.set(null);
    if (!!(cb && cb.constructor && cb.apply)) cb.apply(this, [err, _userId]);
  });
}
```

There's an issue here, almost a sort-of, race condition.

So here's what happens:
1. You impersonate a user.
2. You click on the unimpersonate button.
3. This calls `undo()`.
4. `undo()` calls `do()`, with a callback
5. `do()` runs and calls the `undo()` callback immediately, which sets the `_user` value to `null`.
6. `do()` continues running and as there is no error, then calls:

``` javascript
if (!Impersonate._user.get()) Impersonate._user.set(Meteor.userId()); // First impersonation
Meteor.connection.setUserId(_userId);
```

But by this time, the user **_is**_ null, so it sets it _back_ to the impersonated user's id

**Comment by gwendall** [comment]
Good catch. That should be fixed now.

**Comment by Siyfion** [comment]
Right.. I think this issue is solved, but I still can't unimpersonate now, because the `Impersonate.do()` call returns an error as the user calling unimpersonate isn't an 'admin'. Perhaps a check needs to be put into the server code for allowing the user to set it back as well @gwendall ?

**Comment by gwendall** [comment]
Fixed with 2f6081ad1407c3a5559dfccd49071fe3f21dc98f.

**Comment by Siyfion** [comment]
@gwendall Just as a note, anyone that is running Simple Schema on their users collection will get the following error:

```
W20150324-15:41:26.646(0)? (STDERR) 
W20150324-15:41:26.647(0)? (STDERR) /Users/siyfion/.meteor/packages/meteor-tool/.1.0.44.9goy0n++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20150324-15:41:26.648(0)? (STDERR)                         throw(ex);
W20150324-15:41:26.648(0)? (STDERR)                               ^
W20150324-15:41:26.648(0)? (STDERR) Error: undefined is not allowed by the schema
W20150324-15:41:26.648(0)? (STDERR)     at getErrorObject (packages/aldeed:collection2/collection2.js:363:1)
W20150324-15:41:26.648(0)? (STDERR)     at [object Object].doValidate (packages/aldeed:collection2/collection2.js:346:1)
W20150324-15:41:26.648(0)? (STDERR)     at [object Object].Mongo.Collection.(anonymous function) [as update] (packages/aldeed:collection2/collection2.js:147:1)
W20150324-15:41:26.648(0)? (STDERR)     at Meteor.methods.impersonate.currentUser (packages/gwendall:impersonate/server/lib.js:8:1)
W20150324-15:41:26.648(0)? (STDERR)     at /Users/siyfion/Git/LabelLogicLive/.meteor/local/build/programs/server/boot.js:229:5
=> Exited with code: 8
```

I'm looking into what they need to add now.

EDIT: A simple:

```
  _impersonateToken: {
    type: String,
    optional: true
  }
```

will suffice.

**Comment by gwendall** [comment]
You should add the _impersonateToken key to your schema.

``` javascript
Meteor.users.attachSchema(new SimpleSchema({
  _impersonateToken: {
    type: String,
    optional: true
  }
}));
```
